
library(tidyverse)
library(stringr)
pdb <- read.csv('/Users/nm/Desktop/projects/work/bernie/one-offs/pdb2019bgv3_us.csv')

pdb_tract <- read.csv('/Users/nm/Desktop/projects/work/bernie/one-offs/pdb2019trv3_us.csv')


varlist <- c('GIDBG',
             'State',
             'State_name',
             'County',
             'County_name',
             'Tract',
             'Block_group',
             'Flag',
             'LAND_AREA',
             'AIAN_LAND',
             'Males_ACS_13_17',
             'Females_ACS_13_17',
             'Median_Age_ACS_13_17',
             'Pop_under_5_ACS_13_17',
             'Pop_5_17_ACS_13_17',
             'Pop_18_24_ACS_13_17',
             'Pop_25_44_ACS_13_17',
             'Pop_45_64_ACS_13_17',
             'Pop_65plus_ACS_13_17',
             'Hispanic_ACS_13_17',
             'NH_White_alone_ACS_13_17',
             'NH_Blk_alone_ACS_13_17',
             'NH_AIAN_alone_ACS_13_17',
             'NH_Asian_alone_ACS_13_17',
             'NH_NHOPI_alone_ACS_13_17',
             'NH_SOR_alone_ACS_13_17',
             'Pop_5yrs_Over_ACS_13_17',
             'Othr_Lang_ACS_13_17',
             'Pop_25yrs_Over_ACS_13_17',
             'Not_HS_Grad_ACS_13_17',
             'College_ACS_13_17',
             'Pov_Univ_ACS_13_17',
             'Prs_Blw_Pov_Lev_ACS_13_17',
             'One_Health_Ins_ACS_13_17',
             'Two_Plus_Health_Ins_ACS_13_17',
             'No_Health_Ins_ACS_13_17',
             'Pop_1yr_Over_ACS_13_17',
             'Diff_HU_1yr_Ago_ACS_13_17',
             'ENG_VW_SPAN_ACS_13_17',
             'ENG_VW_INDO_EURO_ACS_13_17',
             'ENG_VW_API_ACS_13_17',
             'ENG_VW_OTHER_ACS_13_17',
             'ENG_VW_ACS_13_17',
             'Rel_Family_HHD_ACS_13_17',
             'MrdCple_Fmly_HHD_ACS_13_17',
             'Not_MrdCple_HHD_ACS_13_17',
             'Female_No_HB_ACS_13_17',
             'NonFamily_HHD_ACS_13_17',
             'Sngl_Prns_HHD_ACS_13_17',
             'HHD_PPL_Und_18_ACS_13_17',
             'Tot_Prns_in_HHD_ACS_13_17',
             'Rel_Child_Under_6_ACS_13_17',
             'HHD_Moved_in_ACS_13_17',
             'PUB_ASST_INC_ACS_13_17',
             'Med_HHD_Inc_BG_ACS_13_17',
             'Med_HHD_Inc_TR_ACS_13_17',
             'Aggregate_HH_INC_ACS_13_17',
             'Tot_Housing_Units_ACS_13_17',
             'Tot_Occp_Units_ACS_13_17',
             'Tot_Vacant_Units_ACS_13_17',
             'Renter_Occp_HU_ACS_13_17',
             'Owner_Occp_HU_ACS_13_17',
             'Single_Unit_ACS_13_17',
             'MLT_U2_9_STRC_ACS_13_17',
             'MLT_U10p_ACS_13_17',
             'Mobile_Homes_ACS_13_17',
             'Crowd_Occp_U_ACS_13_17',
             'Occp_U_NO_PH_SRVC_ACS_13_17',
             'No_Plumb_ACS_13_17',
             'Recent_Built_HU_ACS_13_17',
             'Med_House_Value_BG_ACS_13_17',
             'Med_House_Value_TR_ACS_13_17',
             'Aggr_House_Value_ACS_13_17',
             'Mail_Return_Rate_CEN_2010',
             'Low_Response_Score',
             'pct_Hispanic_ACS_13_17',
             'pct_NH_White_alone_ACS_13_17',
             'pct_NH_Blk_alone_ACS_13_17',
             'pct_NH_AIAN_alone_ACS_13_17',
             'pct_NH_Asian_alone_ACS_13_17',
             'pct_NH_NHOPI_alone_ACS_13_17',
             'pct_NH_SOR_alone_ACS_13_17',
             'pct_Pop_5yrs_Over_ACS_13_17',
             'pct_Othr_Lang_ACS_13_17',
             'pct_Pop_25yrs_Over_ACS_13_17',
             'pct_Not_HS_Grad_ACS_13_17',
             'pct_College_ACS_13_17',
             'pct_Pov_Univ_ACS_13_17',
             'pct_Prs_Blw_Pov_Lev_ACS_13_17',
             'pct_One_Health_Ins_ACS_13_17',
             'pct_TwoPHealthIns_ACS_13_17',
             'pct_No_Health_Ins_ACS_13_17',
             'pct_Pop_1yr_Over_ACS_13_17',
             'pct_Diff_HU_1yr_Ago_ACS_13_17',
             'pct_ENG_VW_SPAN_ACS_13_17',
             'pct_ENG_VW_INDOEURO_ACS_13_17',
             'pct_ENG_VW_API_ACS_13_17',
             'pct_ENG_VW_OTHER_ACS_13_17',
             'pct_ENG_VW_ACS_13_17',
             'pct_Rel_Family_HHD_ACS_13_17',
             'pct_MrdCple_HHD_ACS_13_17',
             'pct_Not_MrdCple_HHD_ACS_13_17',
             'pct_Female_No_HB_ACS_13_17',
             'pct_NonFamily_HHD_ACS_13_17',
             'pct_Sngl_Prns_HHD_ACS_13_17',
             'pct_HHD_PPL_Und_18_ACS_13_17',
             'avg_Tot_Prns_in_HHD_ACS_13_17',
             'pct_Rel_Under_6_ACS_13_17',
             'pct_HHD_Moved_in_ACS_13_17',
             'pct_PUB_ASST_INC_ACS_13_17',
             'avg_Agg_HH_INC_ACS_13_17',
             'pct_Tot_Occp_Units_ACS_13_17',
             'pct_Vacant_Units_ACS_13_17',
             'pct_Renter_Occp_HU_ACS_13_17',
             'pct_Owner_Occp_HU_ACS_13_17',
             'pct_Single_Unit_ACS_13_17',
             'pct_MLT_U2_9_STRC_ACS_13_17',
             'pct_MLT_U10p_ACS_13_17',
             'pct_Mobile_Homes_ACS_13_17',
             'pct_Crowd_Occp_U_ACS_13_17',
             'pct_NO_PH_SRVC_ACS_13_17',
             'pct_No_Plumb_ACS_13_17',
             'pct_Recent_Built_HU_ACS_13_17',
             'avg_Agg_House_Value_ACS_13_17')

varlist2 <- c('GIDTR',
              'State',
              'State_name',
              'County',
              'County_name',
              'Tract',
              'Flag',
              'Num_BGs_in_Tract',
              'LAND_AREA',
              'AIAN_LAND',
              'Tot_Population_ACS_13_17',
              'Median_Age_ACS_13_17',
              'Civ_Noninst_Pop_ACS_13_17',
              'Tot_Prns_in_HHD_ACS_13_17',
              'Med_HHD_Inc_ACS_13_17',
              'Aggregate_HH_INC_ACS_13_17',
              'Med_House_Value_ACS_13_17',
              'pct_College_ACS_13_17',
              'pct_Prs_Blw_Pov_Lev_ACS_13_17',
              'pct_No_Health_Ins_ACS_13_17',
              'pct_Civ_unemp_16p_ACS_13_17',
              'pct_Pop_Disabled_ACS_13_17',
              'pct_Children_in_Pov_ACS_13_17',
              'pct_NoHealthIns_U19_ACS_13_17',
              'pct_NoHealthIns1964_ACS_13_17',
              'pct_NoHealthIns_65P_ACS_13_17',
              'pct_Schl_Enroll_3_4_ACS_13_17',
              'pct_Pop_NoCompDevic_ACS_13_17',
              'pct_Pop_w_BroadComp_ACS_13_17',
              'avg_Tot_Prns_in_HHD_ACS_13_17',
              'pct_PUB_ASST_INC_ACS_13_17',
              'avg_Agg_HH_INC_ACS_13_17',
              'avg_Agg_House_Value_ACS_13_17',
              'pct_MrdCple_w_child_ACS_13_17',
              'pct_HHD_NoCompDevic_ACS_13_17',
              'pct_HHD_w_Computer_ACS_13_17',
              'pct_HHD_w_OnlySPhne_ACS_13_17',
              'pct_HHD_No_Internet_ACS_13_17',
              'pct_HHD_w_Broadband_ACS_13_17',
              'Mail_Return_Rate_CEN_2010',
              'Low_Response_Score',
              'Self_Response_Rate_ACS_13_17')

pdb_2 <- pdb %>% select(varlist) %>%
  mutate_all(function(x) gsub('[$]',"",x)) %>%
  mutate_all(function(x) as.numeric(gsub(',','',x)))  %>%
  dplyr::mutate_all(., funs(replace(., is.na(.), 0)))
pdb_tract_2 <- pdb_tract %>% select(varlist2) %>%
  mutate_all(function(x) gsub('[$]',"",x)) %>%
  mutate_all(function(x) as.numeric(gsub(',','',x))) %>%
  dplyr::mutate_all(., funs(replace(., is.na(.), 0)))%>%
  rename_all(funs(paste0(.,'_tract')) )

pdb_2 %>% select(avg_Agg_House_Value_ACS_13_17)

write_csv(pdb_2, '/Users/nm/Desktop/projects/work/bernie/one-offs/census_pdb_blockgroup.csv')
write_csv(pdb_tract_2, '/Users/nm/Desktop/projects/work/bernie/one-offs/census_pdb_blocktract.csv')
