
INPUT_TABLE <- Sys.getenv('INPUT_TABLE')
OUTPUT_TABLE <- Sys.getenv('OUTPUT_TABLE')
ENABLE_CASS <- Sys.getenv('ENABLE_CASS')
MATCHES_PER_ID <- Sys.getenv('MATCHES_PER_ID')
CUTOFF_THRESHOLD <- Sys.getenv('CUTOFF_THRESHOLD')
REMATCH_THRESHOLD <- Sys.getenv('REMATCH_THRESHOLD')


